name: Ruff

on:
  push:
    paths:
      - "**.py"
      - ".github/workflows/**"
  pull_request:
    paths:
      - "**.py"
      - ".github/workflows/**"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1
